import { useState } from 'react';
import UrgencyBadge from './UrgencyBadge';

function ConsensusDashboard({ consensus, patientData, messages, onNewConsultation }) {
    const [copied, setCopied] = useState(false);

    // Parse the consensus text to extract structured data
    const parseConsensus = (text) => {
        const lines = text.split('\n').filter(line => line.trim());
        let diagnosis = '';
        let confidence = 62; // Default
        let recommendations = [];
        let alternatives = [];

        // Simple parsing - look for patterns
        for (const line of lines) {
            const lowerLine = line.toLowerCase();

            // Look for diagnosis
            if (lowerLine.includes('primary diagnosis') || lowerLine.includes('diagnosis:')) {
                diagnosis = line.replace(/.*diagnosis[:\s]*/i, '').trim();
                // Try to extract percentage
                const percentMatch = line.match(/(\d+)%/);
                if (percentMatch) {
                    confidence = parseInt(percentMatch[1]);
                }
            }

            // Look for numbered recommendations
            if (/^\d+[\.\)]/.test(line.trim())) {
                recommendations.push(line.replace(/^\d+[\.\)]\s*/, '').trim());
            }

            // Look for alternatives
            if (lowerLine.includes('alternative') || lowerLine.includes('differential')) {
                alternatives.push(line);
            }
        }

        // If no structured diagnosis found, use first substantive line
        if (!diagnosis) {
            diagnosis = lines.find(l => l.length > 20 && !l.startsWith('#')) || 'Under evaluation';
        }

        return { diagnosis, confidence, recommendations, alternatives };
    };

    const parsed = parseConsensus(consensus.text);

    const doctorSummary = `${patientData.symptoms}

Pain level: ${patientData.painLevel}/10
Duration: ${patientData.duration}

AI Consultation Summary: ${parsed.diagnosis}
Urgency: ${consensus.urgency?.message || 'Consult healthcare provider'}

This summary was generated by HealthHuddle AI for informational purposes.`;

    const handleCopy = async () => {
        try {
            await navigator.clipboard.writeText(doctorSummary);
            setCopied(true);
            setTimeout(() => setCopied(false), 2000);
        } catch (err) {
            console.error('Copy failed:', err);
        }
    };

    const handleDownloadPDF = () => {
        // Create a simple text-based report (in a real app, use jsPDF)
        const report = `
HEALTHHUDDLE CONSULTATION REPORT
================================
Date: ${new Date().toLocaleDateString()}

PATIENT SYMPTOMS:
${patientData.symptoms}

Pain Level: ${patientData.painLevel}/10
Duration: ${patientData.duration}

TEAM CONSENSUS:
${parsed.diagnosis}
Confidence: ${parsed.confidence}%
Urgency: ${consensus.urgency?.message || 'Consult healthcare provider'}

RECOMMENDATIONS:
${parsed.recommendations.map((r, i) => `${i + 1}. ${r}`).join('\n')}

AGENT DISCUSSION:
${messages.map(m => `[${m.agent}]: ${m.text}`).join('\n\n')}

SOURCES CONSULTED:
${consensus.sources?.map(s => `- ${s.title}`).join('\n') || 'See individual messages'}

---
DISCLAIMER: This report is generated by AI for informational purposes only.
Always consult a qualified healthcare provider for medical decisions.
    `.trim();

        const blob = new Blob([report], { type: 'text/plain' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = 'healthhuddle-report.txt';
        a.click();
        URL.revokeObjectURL(url);
    };

    return (
        <section className="consensus-section">
            <div className="consensus-card glass-panel-elevated">
                {/* Header */}
                <div className="consensus-header">
                    <div className="consensus-title">
                        <span className="consensus-icon">🎯</span>
                        <div>
                            <h2>Team Consensus</h2>
                            <p className="text-muted">All 4 agents have weighed in</p>
                        </div>
                    </div>
                    <UrgencyBadge urgency={consensus.urgency} />
                </div>

                {/* Primary Diagnosis */}
                <div className="diagnosis-box">
                    <div className="diagnosis-label">Primary Assessment</div>
                    <div className="diagnosis-name">{parsed.diagnosis}</div>
                    <div className="diagnosis-confidence">
                        <div className="confidence-bar">
                            <div
                                className="confidence-fill"
                                style={{ width: `${parsed.confidence}%` }}
                            />
                        </div>
                        <span className="confidence-text">{parsed.confidence}% confidence</span>
                    </div>
                </div>

                {/* Full Consensus Text */}
                <div className="recommendations">
                    <h3>📋 Team Summary</h3>
                    <div className="message-bubble consensus" style={{ animation: 'none', opacity: 1, transform: 'none' }}>
                        <div className="message-content" style={{ whiteSpace: 'pre-wrap' }}>
                            {consensus.text}
                        </div>
                    </div>
                </div>

                {/* Recommendations */}
                {parsed.recommendations.length > 0 && (
                    <div className="recommendations">
                        <h3>✅ Next Steps</h3>
                        <ul className="recommendations-list">
                            {parsed.recommendations.slice(0, 5).map((rec, index) => (
                                <li key={index} className="recommendation-item">
                                    <span className="recommendation-number">{index + 1}</span>
                                    <span>{rec}</span>
                                </li>
                            ))}
                        </ul>
                    </div>
                )}

                {/* Doctor Summary */}
                <div className="doctor-summary">
                    <h4>📝 What to Tell Your Doctor</h4>
                    <div className="doctor-summary-text">
                        {doctorSummary}
                    </div>
                    <button className="copy-button" onClick={handleCopy}>
                        {copied ? '✓ Copied!' : '📋 Copy to Clipboard'}
                    </button>
                </div>

                {/* Sources */}
                {consensus.sources && consensus.sources.length > 0 && (
                    <div className="sources-section">
                        <h4>🔍 Sources Consulted ({consensus.sources.length})</h4>
                        <div className="sources-list">
                            {consensus.sources.map((source, index) => (
                                <span key={index} className="source-pill">
                                    <span className="source-icon">{source.icon}</span>
                                    {source.title}
                                </span>
                            ))}
                        </div>
                    </div>
                )}

                {/* Action Buttons */}
                <div className="action-buttons">
                    <button className="action-button primary" onClick={handleDownloadPDF}>
                        📄 Download Report
                    </button>
                    <button className="action-button secondary" onClick={onNewConsultation}>
                        🔄 New Consultation
                    </button>
                </div>
            </div>
        </section>
    );
}

export default ConsensusDashboard;
